config:
  accumulate_grad_batches: 16
  attention_dropout: 0.4
  audio_only: false
  audio_patch_size:
  - 16
  - 16
  audio_size: 1024
  batch_size: 64
  beta1: 0.9
  beta2: 0.999
  data_root: /home/mz/demo/TVLT/Dataset/cmumosei/
  datasets:
  - mosei
  decay_power: 1
  decoder_hidden_size: 512
  draw_false_audio: 0
  draw_false_text: 0
  draw_false_video: 0
  drop_rate: 0.4
  early_stopping_min_delta: 0.001
  early_stopping_patience: 5
  eps: 1.0e-08
  exp_name: cls_mosei
  fast_dev_run: false
  frame_masking: false
  frequency_size: 128
  fusion_type: concat
  get_va_recall_metric: false
  gpus: 1
  gradient_clip_val: 0.5
  hidden_dropout: 0.4
  hidden_size: 768
  learning_rate: 5.0e-05
  load_hub_path: ''
  load_local_path: /home/mz/demo/MyNet/TVLT-MOSEI-SA.ckpt
  log_dir: /home/mz/demo/MyNet/tensorboardlog
  loss_names:
    mae_audio: 0
    mae_video: 0
    mlm: 0
    mosei: 1
    moseiemo: 0
    vam: 0
    vatr: 0
    vqa: 0
    vtm: 0
  lr_scheduler: cosine_warmup
  max_audio_patches: 1020
  max_epoch: 10
  max_frames: 64
  max_steps: 1000000
  max_text_len: 197
  min_lr_ratio: 0.05
  mlm_prob: 0.15
  mlp_ratio: 4.0
  model_type: mae_vit_base_patch16_dec512d8b
  normalize_before: true
  num_frames: 8
  num_heads: 12
  num_layers: 12
  num_nodes: 1
  num_workers: 16
  optim_type: adamw
  patch_size: 16
  per_gpu_batchsize: 1
  seed: 0
  skip_interval: 2
  strict_load: false
  test_only: false
  tokenizer: /home/mz/demo/MyNet/bert
  use_audio: true
  use_mae: false
  use_text: true
  use_video: true
  val_check_interval: 0.5
  video_only: false
  video_size: 224
  vocab_size: 30522
  vqav2_label_size: 3129
  warmup_ratio: 0.15
  warmup_steps: 2000
  weight_decay: 0.05
  whole_word_masking: false
model_type: transformer
